[package]
name = "nu_plugin_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26.4"
nu-plugin = "0.89.0"
nu-protocol = "0.89.0"
serde = "1.0.195"
serde_json = "1.0.111"
